# Pinact configuration for 1-Click GitHub Security
# Controls SHA pinning validation for GitHub Actions workflows
# Documentation: https://github.com/suzuki-shunsuke/pinact

version: 3

# GitHub requires reusable workflows to use semantic version tags, not commit SHAs.
# This is a platform requirement, not a security weakness.
# Reference: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
#
# The SLSA generator workflow provides cryptographic attestation that supersedes
# commit SHA pinning - it's actually MORE secure than pinning.
#
# Therefore, we exclude the SLSA reusable workflow call from pinact validation.
ignore_actions:
  - name: slsa-framework/slsa-github-generator/\.github/workflows/generator_generic_slsa3\.yml
    ref: .*
