site_name: 1-Click GitHub Security v0.4.12
repo_url: https://github.com/h4x0r/1-click-github-sec
site_description: Security controls for multi-language GitHub projects
site_author: Albert Hui <albert@securityronin.com>
copyright: Copyright &copy; 2025 Albert Hui, Security Ronin
theme:
  name: material
  logo: 1-click-github-sec Logo.png
  favicon: 1-click-github-sec Logo.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
nav:
  - 🏠 Home: index.md
  - 🚀 Get Started:
    - Installation Guide: installation.md
    - Uninstall Guide: uninstall.md
  - 🔧 Power User Guides:
    - Security Architecture: architecture.md
    - Cryptographic Verification: cryptographic-verification.md
    - YubiKey + Hardware: yubikey-integration.md
  - 👥 Development:
    - Contributing: contributing.md
    - Repository Security: repo-security.md
    - Design Principles: design-principles.md
    - Sync Strategy: repo-and-installer-sync-strategy.md
