site_name: 1-Click Rust Security Controls
repo_url: https://github.com/h4x0r/1-click-rust-sec
site_description: Fast pre-push security + comprehensive CI for Rust and general repos
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
nav:
  - Home: index.md
  - Installation: installation.md
  - Architecture: architecture.md
  - YubiKey + Sigstore: yubikey.md
  - Uninstall: uninstall.md
