site_name: 1-Click GitHub Security v0.4.2
repo_url: https://github.com/h4x0r/1-click-github-sec
site_description: Security controls for multi-language GitHub projects
site_author: Albert Hui <albert@securityronin.com>
copyright: Copyright &copy; 2025 Albert Hui, Security Ronin
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
nav:
  - Home: index.md
  - Installation Guide: installation.md
  - Security Architecture: architecture.md
  - Cryptographic Signing:
    - YubiKey + Sigstore Setup: yubikey.md
    - Signed Commits & Tags: signing.md
    - Certificate Transparency: transparency.md
  - Advanced Topics:
    - Repository Security: repo-security.md
    - Design Principles: design-principles.md
  - Maintenance:
    - Uninstall Guide: uninstall.md
    - Contributing: contributing.md
