site_name: 1-Click Rust Security Controls
repo_url: https://github.com/4n6h4x0r/1-click-rust-sec
site_description: Fast pre-push security + comprehensive CI for Rust and general repos
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Architecture: architecture.md
  - YubiKey + Sigstore: yubikey.md
  - Uninstall: uninstall.md
