name: Docs Build

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build MkDocs site
        run: |
          set -euo pipefail
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          mkdocs build --strict -d site

      - name: Check links (Markdown) with lychee
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            --config lychee.toml
            docs/**/*.md README.md SECURITY_CONTROLS_INSTALLATION.md SECURITY_CONTROLS_ARCHITECTURE.md docs/security/*.md

      - name: Upload site artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mkdocs-site
          path: site/
