name: Pinning Validation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/**'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-update-pins:
    name: Validate and update SHA pins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate pinned SHAs are reachable
        id: validate
        run: |
          set +e  # Don't exit on first error
          INVALID_SHAS=()

          echo "🔍 Validating pinned SHAs in workflow files..."

          # Extract all SHA-pinned actions from workflow files
          while IFS= read -r line; do
            if [[ "$line" =~ uses:[[:space:]]*([^@]+)@([a-f0-9]{40}) ]]; then
              action="${BASH_REMATCH[1]}"
              sha="${BASH_REMATCH[2]}"

              # Check if SHA exists (use GitHub API to avoid rate limits on git)
              repo_path=$(echo "$action" | cut -d'/' -f1-2)

              echo "Checking $repo_path @ $sha..."

              # Try to fetch commit info from GitHub API
              status_code=$(curl -s -o /dev/null -w "%{http_code}" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/$repo_path/commits/$sha")

              if [[ "$status_code" != "200" ]]; then
                echo "❌ Invalid SHA: $action@$sha (HTTP $status_code)"
                INVALID_SHAS+=("$action@$sha")
              else
                echo "✅ Valid: $action@$sha"
              fi
            fi
          done < <(find .github/workflows -name "*.yml" -o -name "*.yaml" | xargs cat)

          if [[ ${#INVALID_SHAS[@]} -gt 0 ]]; then
            echo "invalid=true" >> $GITHUB_OUTPUT
            echo "count=${#INVALID_SHAS[@]}" >> $GITHUB_OUTPUT
            echo ""
            echo "⚠️  Found ${#INVALID_SHAS[@]} invalid SHA(s):"
            printf '%s\n' "${INVALID_SHAS[@]}"
          else
            echo "invalid=false" >> $GITHUB_OUTPUT
            echo "✅ All pinned SHAs are valid"
          fi

      - name: Create issue for invalid SHAs
        if: steps.validate.outputs.invalid == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const title = '🚨 Invalid SHA pins detected in GitHub Actions workflows';
            const body = `## Problem

            The weekly SHA validation check found ${{ steps.validate.outputs.count }} invalid/unreachable commit SHA(s) in our workflow files.

            This typically happens when:
            - A commit was force-pushed over or deleted from the source repository
            - A tag was moved to a different commit
            - The repository had history rewritten

            ## Solution

            Renovate should automatically fix these in its next run. If not, manually update the affected workflows to use current valid SHAs.

            ## Check Logs

            See the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

            This issue will be automatically closed when all SHAs are valid.`;

            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['invalid-sha-pins']
            });

            if (issues.data.length === 0) {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['invalid-sha-pins', 'dependencies', 'security']
              });
            }

      - name: Close issue if all SHAs valid
        if: steps.validate.outputs.invalid == 'false'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            // Find and close any open invalid-sha-pins issues
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['invalid-sha-pins']
            });

            for (const issue of issues.data) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: '✅ All SHA pins are now valid. Closing this issue automatically.'
              });
            }
