name: Shell Lint

on:
  pull_request:
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install shellcheck and shfmt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck shfmt

      - name: ShellCheck
        run: |
          set -euo pipefail
          # Fail on warnings and errors
          find . -type f -name "*.sh" -not -path "./.git/*" -print0 | xargs -0 -r shellcheck -S warning

      - name: shfmt (diff-only)
        run: |
          set -euo pipefail
          # Check formatting with 2-space indent, simplify, and case indent
          shfmt -d -i 2 -ci -s .
